### ISSUE TITLE
An error occured during connecting: TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by asepwaee** [saifulcoder/laravel-whatsapp-server#1]
izin mas, sebelum nya terimakasih atas projectnya. 
ini saya bikin issu terkait error di local. barangkali bisa sama2 kita perbaiki

case : ketika scan barcode menggunakan hp. muncul error seperti itu diterminal backend

terimakasih

**Comment by saifulcoder** [comment]
bisa ditampilkan lebih detail errornya ada ss nya?

**Comment by asepwaee** [comment]
@saifulcoder 
![wajserror](https://user-images.githubusercontent.com/26277417/152778153-841ac5ad-c71e-40cb-a852-c10cdd615b36.png)

ini mas, terminal backend langsung force close setelah error ini

**Comment by asepwaee** [comment]
@saifulcoder 
![fe error](https://user-images.githubusercontent.com/26277417/152778806-a03b2422-2e33-44e7-b279-f0798a770141.png)

ini error di laravelnya mas.

**Comment by asepwaee** [comment]
mas @saifulcoder sepertinya error ini karena whatspp beta multidevice. soalnya pas saya keluar dari beta multi device normal. no error

**Comment by ookamiiixd** [comment]
@asepwaee kemungkinan iya mas, karena memang versi library Baileys yang saya gunakan belum support beta multi device.

**Comment by asepwaee** [comment]
@ookamiiixd @saifulcoder 
Oke mas. Thanks issue closed berarti ya 
Trimakasih
