### ISSUE TITLE
PHP 8: ErrorException Undefined variable $style_css (View:

### ISSUE THREAD

**Issue by SaidMoulla** [saifulcoder/laravel-whatsapp-server#13]
Hello dear!
How can we solve the ERROR shown in PHP 8?
`ErrorException Undefined variable $style_css (View:....`

When we downgrade the PHP from V8 to version: 7.4.2 ..... the error SOLVED!

BUT, there is an other ERROR, when creating new Device and trying to access "devices" page from menu can't reach it after a long waiting time to loading but Server not respond..

Many thanks for your efforts.

**Comment by saifulcoder** [comment]
requirment php 7.4
