### ISSUE TITLE
qrcode gak bisa discan required multidevice

### ISSUE THREAD

**Issue by kopigreenx** [saifulcoder/laravel-whatsapp-server#14]
`{
  "output": {
    "statusCode": 411,
    "payload": {
      "statusCode": 411,
      "error": "Length Required",
      "message": "Require multi-device edition"
    },
    "headers": {}
  }
}`

pass scan QR gagal terus ternyata parameter multidevicenya harus active ,gimana cara aktifin multidevicenya ya mas ?

**Comment by asepwaee** [comment]
iya sama, apakah ada yg harus disetting lagi biar support MD ?

**Comment by asepwaee** [comment]
> `{ "output": { "statusCode": 411, "payload": { "statusCode": 411, "error": "Length Required", "message": "Require multi-device edition" }, "headers": {} } }`
> 
> pass scan QR gagal terus ternyata parameter multidevicenya harus active ,gimana cara aktifin multidevicenya ya mas ?

solved mas. kalo mau pake multidevicenya di AdminDeviceController.php isLegacy set jadi false.

**Comment by saifulcoder** [comment]
> > `{ "output": { "statusCode": 411, "payload": { "statusCode": 411, "error": "Length Required", "message": "Require multi-device edition" }, "headers": {} } }`
> > 
> > pass scan QR gagal terus ternyata parameter multidevicenya harus active ,gimana cara aktifin multidevicenya ya mas ?
> 
> solved mas. kalo mau pake multidevicenya di AdminDeviceController.php isLegacy set jadi false.

Oke makasih mas Insya Allah segera update

**Comment by asepwaee** [comment]
> > > `{ "output": { "statusCode": 411, "payload": { "statusCode": 411, "error": "Length Required", "message": "Require multi-device edition" }, "headers": {} } }`
> > > 
> > > pass scan QR gagal terus ternyata parameter multidevicenya harus active ,gimana cara aktifin multidevicenya ya mas ?
> > 
> > solved mas. kalo mau pake multidevicenya di AdminDeviceController.php isLegacy set jadi false.
> 
> Oke makasih mas Insya Allah segera update

Siap mas, menurut saya sudah pas seperti itu. Defaultnya legacy. Barangkali tambah dokumentasinya saja, yg mau pake MD tinggal di rubah saja.

**Comment by saifulcoder** [comment]
sudah saya update untuk pilihan multidevice atau yang web
