### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by drdaga** [saifulcoder/laravel-whatsapp-server#18]
Hello i just saw you demo on youtube and came over here
needed to knw installtions process as u mentioned to enter database username and password which database username and password ??
I mean which type mysql , PostgreSQL ??
if any1 cud quide detailed installation demo it will be very helpfull

**Comment by AnandMasabinal** [comment]
use mysql

**Comment by saifulcoder** [comment]
> at

i was upload installation tutorial in my youtube
https://youtu.be/hXWKCHyaUgY

**Comment by AnandMasabinal** [comment]
Hi Saifulcoder
can u resolve new update whatsapp version Beta QR scaning

**Comment by AnandMasabinal** [comment]
Please help me

**Comment by saifulcoder** [comment]
> Hi Saifulcoder can u resolve new update whatsapp version Beta QR scaning

use my backend folder

**Comment by AnandMasabinal** [comment]
thanks saifulcoder.. i want to know attach image could you help me please
