### ISSUE TITLE
proses migrasi pada database terjadi error  Illuminate\Database\QueryException

### ISSUE THREAD

**Issue by Helwieahmad** [saifulcoder/laravel-whatsapp-server#20]
halo, saya mengalami error ketika mencoba migrasi database dengan error  Illuminate\Database\QueryException

 SQLSTATE[HY000]: General error: 1025 Error on rename of '.\whatsapp_server\#sql-107c_316' to '.\whatsapp_server\cms_settings' (errno: 13 "Permission denied") (SQL: alter table `cms_settings` add `label` varchar(255) null)

  at C:\xampp\htdocs\laravel-whatsapp-server\vendor\laravel\framework\src\Illuminate\Database\Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }

  1   C:\xampp\htdocs\laravel-whatsapp-server\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDO\Exception.php:18
      Doctrine\DBAL\Driver\PDO\Exception::("SQLSTATE[HY000]: General error: 1025 Error on rename of '.\whatsapp_server\#sql-107c_316' to '.\whatsapp_server\cms_settings' (errno: 13 "Permission denied")")

  2   C:\xampp\htdocs\laravel-whatsapp-server\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:119
      Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))

**Comment by zakirkun** [comment]
Permission user databasenya mas

**Comment by Helwieahmad** [comment]
> Permission user databasenya mas

untuk create table yang lain bisa, nah pas sampai di cms_settings errornya sprt itu. kira2 apa masalahnya ya
