### ISSUE TITLE
tidak bisa melakukan proses migrate:fresh -seed

### ISSUE THREAD

**Issue by timitp2s3** [saifulcoder/laravel-whatsapp-server#21]
saya menggunakan windows dengan instalasi xampp terbaru ketika eksekusi utk migration database muncul error seperti ini
Migrating: 2016_09_16_045425_add_label_setting

   Illuminate\Database\QueryException

  SQLSTATE[HY000]: General error: 1025 Error on rename of '.\whatsapp\#sql-12a4_7d' to '.\whatsapp\cms_settings' (errno: 13 "Permission denied") (SQL: alter table `cms_settings` add `label` varchar(255) null)

  at C:\xampp\htdocs\whatsapp\vendor\laravel\framework\src\Illuminate\Database\Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }

  1   C:\xampp\htdocs\whatsapp\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDO\Exception.php:18
      Doctrine\DBAL\Driver\PDO\Exception::("SQLSTATE[HY000]: General error: 1025 Error on rename of '.\whatsapp\#sql-12a4_7d' to '.\whatsapp\cms_settings' (errno: 13 "Permission denied")")

  2   C:\xampp\htdocs\whatsapp\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:119
      Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))

kira-kira dimana letak masalahnya?

**Comment by Helwieahmad** [comment]
saya juga mengalami hal yang sama, bahkan saya coba melakukan migrate di versin windows 10.11 dan linux

**Comment by saifulcoder** [comment]
sudah coba pakai user root?

**Comment by Helwieahmad** [comment]
> sudah coba pakai user root?

Kalau settingan posisi user sudah menggunakan root pak

**Comment by Helwieahmad** [comment]
maaf sebelumnya, mungkin kalau boleh mengusulkan sebagai alternatif tidak bisa melakukan migrate disertkan file backup dataabasenya ya gan

**Comment by saifulcoder** [comment]
oke sudah saya upload databasenya

**Comment by timitp2s3** [comment]
> oke sudah saya upload databasenya

wah terima kasih pak,
dixampp yg saya coba berakali2 mmg error di proses migrasinya. tp ketika saya hapus xampp dan ganti menggunakan laragon sukses
