### ISSUE TITLE
no code generated

### ISSUE THREAD

**Issue by drdaga** [saifulcoder/laravel-whatsapp-server#24]
even after clining scaning no code is getting generated can u please help ??

![image](https://user-images.githubusercontent.com/45959508/166223080-008683d5-4c69-41f7-8166-4ef5b04b56c4.png)

**Comment by saifulcoder** [comment]
Use ip public for backend

**Comment by drdaga** [comment]
i used my server website
now following weeror when i try to access it

![image](https://user-images.githubusercontent.com/45959508/166229477-85723fbf-0946-4b83-8312-d6547722e37d.png)

**Comment by drdaga** [comment]
already URL_WA_SERVER=http://whatsapp.imaginewebstudio.com:8000

![image](https://user-images.githubusercontent.com/45959508/166232354-16124884-e777-4955-96eb-57bac15102d9.png)

**Comment by saifulcoder** [comment]
You can access with request by postman

**Comment by drdaga** [comment]
same error with postman 
![image](https://user-images.githubusercontent.com/45959508/166233816-dfd43ef8-e855-4d18-a989-ec3c8a82ada0.png)

**Comment by saifulcoder** [comment]
Session/add
Without "s"
Import postman.json in my backend folder
