### ISSUE TITLE
Gak bisa install dependencynya pak

### ISSUE THREAD

**Issue by RAYHunts** [saifulcoder/laravel-whatsapp-server#26]
Problem 1
    - crocodicstudio/crudbooster is locked to version v5.6.2 and an update of this package was not requested.
    - crocodicstudio/crudbooster v5.6.2 requires php ^7.4 -> your php version (8.1.6) does not satisfy that requirement.        
  Problem 2
    - dompdf/dompdf is locked to version v0.8.6 and an update of this package was not requested.
    - dompdf/dompdf v0.8.6 requires php ^7.1 -> your php version (8.1.6) does not satisfy that requirement.
  Problem 3
    - phpoffice/phpspreadsheet is locked to version 1.21.0 and an update of this package was not requested.
    - phpoffice/phpspreadsheet 1.21.0 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
  Problem 4
    - dompdf/dompdf v0.8.6 requires php ^7.1 -> your php version (8.1.6) does not satisfy that requirement.
    - barryvdh/laravel-dompdf v0.8.7 requires dompdf/dompdf ^0.8 -> satisfiable by dompdf/dompdf[v0.8.6].
    - barryvdh/laravel-dompdf is locked to version v0.8.7 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-gd` to temporarily ignore these required extensions.

**Comment by saifulcoder** [comment]
Requirment php versi 7.4
