### ISSUE TITLE
Tidak dapat scan qr

### ISSUE THREAD

**Issue by kingrootid** [saifulcoder/laravel-whatsapp-server#27]
QR tampil tapi tidak bisa discan atau tidak valid waktu scan di app whatsapp nya

terima kasih

**Comment by saifulcoder** [comment]
Jeda 20 detik untuk reload qr 
Default dari whatasapp

**Comment by kingrootid** [comment]
ya kalau itu emang reload
tapi untuk scan dari hp ke qr nya itu tidak bisa

**Comment by kingrootid** [comment]
![Uploading 6332A720-C93A-42A7-B17A-046EB6513721.jpeg…]()

**Comment by saifulcoder** [comment]
gak bisa dibuka

**Comment by kingrootid** [comment]
https://imgur.com/a/rLuaLuh

**Comment by asepwaee** [comment]
sya mengalami case yang sama, tidak berhasil masuk saat scan
notifikasi dari aplikasi whatsapp:
"tidak dapat masuk, periksa koneksi internet telepon anda dan pindai kode QR lagi

**Comment by saifulcoder** [comment]
Kalo scan lewat terminal bisa?

**Comment by asepwaee** [comment]
belum dicoba mas, sepertinya ada bug dari baileys api nya.
di repo [@ookamiiixd/baileys-api](https://github.com/ookamiiixd/baileys-api) ada issue yang sama tidak bisa scan qr 
case ini setelah saya update wa ke versi terbaru, sebelumnya pake WA beta masih bisa

**Comment by saifulcoder** [comment]
Coba masuk admin laravel
Device -> edit
Multidevice di ganti yes
Scan ulang

**Comment by asepwaee** [comment]
@saifulcoder sudah mas, ini baru coba lewat teriminal juga masih tidak bisa.  pake app wa terbaru di playstore.

**Comment by saifulcoder** [comment]
Sudah di update folder backendnya?
`npm u`

**Comment by kingrootid** [comment]
saya yang report issue itu juga. di repo backend nya. 
belum solve

**Comment by saifulcoder** [comment]
Report issue ke baileys nya langsung aja
https://github.com/adiwajshing/Baileys

**Comment by bintaroweb** [comment]
Ini link diskusi reponya om saifulcoder, mungkin bisa membantu menemukan letak kendalanya dimana 

https://github.com/ookamiiixd/baileys-api/issues/44

**Comment by LapakArduino** [comment]
coba pakai alternate ini https://github.com/WhiskeySockets/Baileys
