### ISSUE TITLE
Connected sebelum Scan QR Code

### ISSUE THREAD

**Issue by DodiDT** [saifulcoder/laravel-whatsapp-server#31]
![image](https://user-images.githubusercontent.com/52699992/178625932-535a8d1e-2f08-4316-a349-3b0391ad6b30.png)

**Comment by DodiDT** [comment]
Saat masuk ke menu Scan, kemudian back ke menu device (tanpa scan QR Code) status otomatis menjadi connected

**Comment by saifulcoder** [comment]
bug dari plugin baileys
dia baca session ready walaupun baru request qr tapi jeda 20 detik dia normal
