### ISSUE TITLE
Tidak Keluar QR Code

### ISSUE THREAD

**Issue by ktiprob** [saifulcoder/laravel-whatsapp-server#33]
![image](https://user-images.githubusercontent.com/87354327/180150577-9c9e1f18-dc18-4b2a-ad7f-1d66c49e8186.png)
tidak keluar qr code gimana solusinya?

**Comment by saifulcoder** [comment]
install ulang
coba hapus semua file

**Comment by romiardisaja** [comment]
mengalami hal yang sama, fresh install di folder baaru, juga tidak keluar QR Code.

**Comment by mdestafadilah** [comment]
jangan lupa .ENV frontend dicek, apakah sudah mengarah ke backend,

```bash
URL_WA_SERVER=http://localhost:3000
```

Noted: wa server pastikan jangan pake domain melainkan 1 server dengan aplikasi frontend.
