### ISSUE TITLE
Kok tidak bisa di RUN di hosting ya ?

### ISSUE THREAD

**Issue by zeeid** [saifulcoder/laravel-whatsapp-server#34]

**Comment by zeeid** [comment]
Hosting padahal support nodejs juga

**Comment by saifulcoder** [comment]
Gak smua shared hosting ngasih full akses om.
Hostingya dmn om?

**Comment by zeeid** [comment]
di CPanel ada nodejs nya
roqie.com

**Comment by zeeid** [comment]
Backend nya kyak gini trus hasilnya

503
Service Unavailable

The server is temporarily busy, try again later!
