### ISSUE TITLE
Migrate to Whatsapp-web.js Module, baileys Depreciated, in that state baileys module will more likely make your account get banned by WA

### ISSUE THREAD

**Issue by hendradra1234** [saifulcoder/laravel-whatsapp-server#41]
Can we Migrate this project to use Whatsapp-web.js because of baileys discontinuation

**Comment by mdestafadilah** [comment]
> Can we Migrate this project to use Whatsapp-web.js because of baileys discontinuation

no migration, just use `"@adiwajshing/baileys": "github:WhiskeySockets/Baileys", change in your package.json.

I know it's not allready, but, it's the recomendation. or... if you need more stable using `4.4.0` but it's not a recomendation.
