### ISSUE TITLE
Getting "stream errored out" on try to connect

### ISSUE THREAD

**Issue by Cristianogc** [saifulcoder/laravel-whatsapp-server#43]
When trying to read a qrcode and connect a device, the API is returning the following error:

{"level":50,"time":1686253233756,"pid":500336,"hostname":"ip-172-31-12-30","node":{"tag":"stream:error","attrs":{"code":"515"}},"msg":"stream errored out"}
Reconnecting...

something similar is happening in this library:
https://github.com/WhiskeySockets/Baileys/issues/107

**Comment by Azlan-saja** [comment]
![image](https://github.com/saifulcoder/laravel-whatsapp-server/assets/64555230/7e88e2ca-46a7-463c-a145-1292bd6af399)

1. Insert version: [2,2323,4] in  const socket

2. npm run build

**Comment by Cristianogc** [comment]
> ![image](https://user-images.githubusercontent.com/64555230/245294864-7e88e2ca-46a7-463c-a145-1292bd6af399.png)
> 
> 1. Insert version: [2,2323,4] in  const socket
> 2. npm run build

thank you very much. I adapted the script as follows in the whatsapp.js file:

`
    const waConfig = {
        version: [2, 2323, 4],
        auth: state,
        printQRInTerminal: true,
        logger,
        browser: Browsers.ubuntu('Chrome'),
    }`

**Comment by Azlan-saja** [comment]
> 

Solved?

**Comment by Marouane-AQUIL** [comment]
not solved for me

**Comment by saifulcoder** [comment]
change package.json
```
"@adiwajshing/baileys": "^5.0.0",
"@ookamiiixd/baileys-store": "^1.0.0-beta.0",
```
to
```
"@adiwajshing/baileys": "github:whiskeysockets/baileys",
"@ookamiiixd/baileys-store": "github:saifulcoder/baileys-store",
```
delete package-lock.json and folder node_modules
then reinstall

**Comment by Marouane-AQUIL** [comment]
@saifulcoder 

i change that : 
"@adiwajshing/baileys": "github:whiskeysockets/baileys",
"@ookamiiixd/baileys-store": "github:saifulcoder/baileys-store",

and i have this problm now, how i can resolve it:
![image](https://github.com/saifulcoder/laravel-whatsapp-server/assets/42839897/e090837e-661d-43a7-ad4d-017f784791ca)

**Comment by saifulcoder** [comment]
> @saifulcoder
> 
> i change that : "@adiwajshing/baileys": "github:whiskeysockets/baileys", "@ookamiiixd/baileys-store": "github:saifulcoder/baileys-store",
> 
> and i have this problm now, how i can resolve it: ![image](https://user-images.githubusercontent.com/42839897/246578041-e090837e-661d-43a7-ad4d-017f784791ca.png)

i also encountered the same thing and i cant fix it because i am not expert in node js
but that doesn't matter
now try to run
`npm run start`
