### ISSUE TITLE
qr code tidak muncul

### ISSUE THREAD

**Issue by diazzaid** [saifulcoder/laravel-whatsapp-server#6]
error nya seperti ini 
![image](https://user-images.githubusercontent.com/25816482/155155090-cd0225e4-e6f5-4304-b85b-40a6796b9838.png)
mohon bantuan nya agan2

**Comment by saifulcoder** [comment]
> error nya seperti ini ![image](https://user-images.githubusercontent.com/25816482/155155090-cd0225e4-e6f5-4304-b85b-40a6796b9838.png) mohon bantuan nya agan2

ini frontend nya
backendnya udah jalan belum?

**Comment by diazzaid** [comment]
> > error nya seperti ini ![image](https://user-images.githubusercontent.com/25816482/155155090-cd0225e4-e6f5-4304-b85b-40a6796b9838.png) mohon bantuan nya agan2
> 
> ini frontend nya backendnya udah jalan belum?

Sudah mas, port nya yg 8000 kan ya, tp gk ada log apapun di backend baileys nya

**Comment by saifulcoder** [comment]
> > > error nya seperti ini ![image](https://user-images.githubusercontent.com/25816482/155155090-cd0225e4-e6f5-4304-b85b-40a6796b9838.png) mohon bantuan nya agan2
> > 
> > 
> > ini frontend nya backendnya udah jalan belum?
> 
> Sudah mas, port nya yg 8000 kan ya, tp gk ada log apapun di backend baileys nya

Masuk folder backend 
`npm update`
`npm .`

**Comment by diazzaid** [comment]
qr code sudah muncul tp sy add nya via post backendnya lgsg mas
klo lwt laravel nya gk ada .. jd seperti dari laravel nya tidak terhubung ke backend

**Comment by diazzaid** [comment]
oia ini sy ada yang salah, backend nya lgsg ngambil dari repo https://github.com/ookamiiixd/baileys-api
pdhl di dalam folder laravel sudah ada folder backend haha
ok d coba lagi mas

**Comment by diazzaid** [comment]
sip sudah bisa mas,,
nuhun
