### ISSUE TITLE
error: php artisan migrate:fresh --seed

### ISSUE THREAD

**Issue by ariessetiyawan** [saifulcoder/laravel-whatsapp-server#8]
mohon solusi ketika menjalanakan php artisan migrate:fresh --seed ada error spt dibawah..

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `personal_access_tokens` add index `personal_access_tokens_tokenable_type_tokenable_id_index`(`tokenable_type`, `tokenable_id`))

**Comment by saifulcoder** [comment]
> SQLSTATE[42000]: Syntax error or access violation: 1071
coba ini pak
https://stackoverflow.com/questions/42244541/laravel-migration-error-syntax-error-or-access-violation-1071-specified-key-wa
